<?php
/**
 * CouponTargetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 21-02-2024 14:48
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DillerAPI;

use PHPUnit\Framework\TestCase;

/**
 * CouponTargetTest Class Doc Comment
 *
 * @category    Class
 * @description Defines where the coupon can be applied to.  The filters are cumulativelly applied.
 * @package     DillerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CouponTargetTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CouponTarget"
     */
    public function testCouponTarget()
    {
    }

    /**
     * Test attribute "requiredPoints"
     */
    public function testPropertyRequiredPoints()
    {
    }

    /**
     * Test attribute "membershipLevel"
     */
    public function testPropertyMembershipLevel()
    {
    }

    /**
     * Test attribute "listId"
     */
    public function testPropertyListId()
    {
    }
}
