<?php
/**
 * CreateTransactionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 27-02-2024 08:24
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DillerAPI;

use PHPUnit\Framework\TestCase;

/**
 * CreateTransactionRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateTransactionRequest
 * @package     DillerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateTransactionRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateTransactionRequest"
     */
    public function testCreateTransactionRequest()
    {
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "paymentDetails"
     */
    public function testPropertyPaymentDetails()
    {
    }

    /**
     * Test attribute "eftPos"
     */
    public function testPropertyEftPos()
    {
    }

    /**
     * Test attribute "sendEmailReceipt"
     */
    public function testPropertySendEmailReceipt()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "totalTax"
     */
    public function testPropertyTotalTax()
    {
    }

    /**
     * Test attribute "totalDiscount"
     */
    public function testPropertyTotalDiscount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "roundOffAmount"
     */
    public function testPropertyRoundOffAmount()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "couponCodes"
     */
    public function testPropertyCouponCodes()
    {
    }

    /**
     * Test attribute "stampCardIds"
     */
    public function testPropertyStampCardIds()
    {
    }

    /**
     * Test attribute "stampCards"
     */
    public function testPropertyStampCards()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "departmentId"
     */
    public function testPropertyDepartmentId()
    {
    }
}
