<?php
/**
 * MemberCouponResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 2024-06-04T11:45:23
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DillerAPI;

use PHPUnit\Framework\TestCase;

/**
 * MemberCouponResponseTest Class Doc Comment
 *
 * @category    Class
 * @description MemberCouponResponse
 * @package     DillerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MemberCouponResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MemberCouponResponse"
     */
    public function testMemberCouponResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "externalIds"
     */
    public function testPropertyExternalIds()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "articleNumber"
     */
    public function testPropertyArticleNumber()
    {
    }

    /**
     * Test attribute "validFrom"
     */
    public function testPropertyValidFrom()
    {
    }

    /**
     * Test attribute "validTo"
     */
    public function testPropertyValidTo()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "discountType"
     */
    public function testPropertyDiscountType()
    {
    }

    /**
     * Test attribute "discountValue"
     */
    public function testPropertyDiscountValue()
    {
    }

    /**
     * Test attribute "maxRedemptions"
     */
    public function testPropertyMaxRedemptions()
    {
    }

    /**
     * Test attribute "imageUrl"
     */
    public function testPropertyImageUrl()
    {
    }

    /**
     * Test attribute "productIds"
     */
    public function testPropertyProductIds()
    {
    }

    /**
     * Test attribute "timesRedeemed"
     */
    public function testPropertyTimesRedeemed()
    {
    }
}
