<?php
/**
 * MemberStampCardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 15-02-2024 09:39
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DillerAPI;

use PHPUnit\Framework\TestCase;

/**
 * MemberStampCardTest Class Doc Comment
 *
 * @category    Class
 * @description MemberStampCard
 * @package     DillerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MemberStampCardTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MemberStampCard"
     */
    public function testMemberStampCard()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "articleNumber"
     */
    public function testPropertyArticleNumber()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "requiredPoints"
     */
    public function testPropertyRequiredPoints()
    {
    }

    /**
     * Test attribute "isRestartable"
     */
    public function testPropertyIsRestartable()
    {
    }

    /**
     * Test attribute "requiredStamps"
     */
    public function testPropertyRequiredStamps()
    {
    }

    /**
     * Test attribute "imageUrl"
     */
    public function testPropertyImageUrl()
    {
    }

    /**
     * Test attribute "lastStampText"
     */
    public function testPropertyLastStampText()
    {
    }

    /**
     * Test attribute "productIds"
     */
    public function testPropertyProductIds()
    {
    }

    /**
     * Test attribute "validFrom"
     */
    public function testPropertyValidFrom()
    {
    }

    /**
     * Test attribute "validTo"
     */
    public function testPropertyValidTo()
    {
    }

    /**
     * Test attribute "stampsCollected"
     */
    public function testPropertyStampsCollected()
    {
    }
}
