<?php
/**
 * OriginTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 15-02-2024 09:39
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DillerAPI;

use PHPUnit\Framework\TestCase;

/**
 * OriginTest Class Doc Comment
 *
 * @category    Class
 * @description Represents the origin of the request, by department, employee, system id and channel.  Eg. Employee John Doe at Pos number 10 in the store department \&quot;New York\&quot; submitted this request.
 * @package     DillerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OriginTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Origin"
     */
    public function testOrigin()
    {
    }

    /**
     * Test attribute "systemId"
     */
    public function testPropertySystemId()
    {
    }

    /**
     * Test attribute "employeeId"
     */
    public function testPropertyEmployeeId()
    {
    }

    /**
     * Test attribute "departmentId"
     */
    public function testPropertyDepartmentId()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }
}
