<?php
/**
 * StoreSegmentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 2024-08-12T18:08:52
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DillerAPI;

use PHPUnit\Framework\TestCase;

/**
 * StoreSegmentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description StoreSegmentResponse
 * @package     DillerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoreSegmentResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StoreSegmentResponse"
     */
    public function testStoreSegmentResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "isVisibleToFollower"
     */
    public function testPropertyIsVisibleToFollower()
    {
    }

    /**
     * Test attribute "isRequired"
     */
    public function testPropertyIsRequired()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }
}
