<?php
/**
 * TransactionDetailRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 2024-06-04T11:45:23
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DillerAPI;

use PHPUnit\Framework\TestCase;

/**
 * TransactionDetailRequestTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionDetailRequest
 * @package     DillerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionDetailRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransactionDetailRequest"
     */
    public function testTransactionDetailRequest()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unitPrice"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "unitMeasure"
     */
    public function testPropertyUnitMeasure()
    {
    }

    /**
     * Test attribute "taxPercentage"
     */
    public function testPropertyTaxPercentage()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "totalPrice"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "stampCardIds"
     */
    public function testPropertyStampCardIds()
    {
    }

    /**
     * Test attribute "stampCards"
     */
    public function testPropertyStampCards()
    {
    }

    /**
     * Test attribute "couponCodes"
     */
    public function testPropertyCouponCodes()
    {
    }
}
