<?php
/**
 * NonEligibleProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 15-02-2024 09:39
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DillerAPI;

use DillerAPI\Configuration;
use DillerAPI\ApiException;
use DillerAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NonEligibleProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NonEligibleProductsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addBatchNonEligibleProducts
     *
     * Add a batch of non-eligible products for a specific store, with a maximum limit of 100 products..
     *
     */
    public function testAddBatchNonEligibleProducts()
    {
    }

    /**
     * Test case for deleteNonEligibleProduct
     *
     * Deletes a non-eligible product..
     *
     */
    public function testDeleteNonEligibleProduct()
    {
    }

    /**
     * Test case for getNonEligibleProducts
     *
     * Gets a paginated list of non-eligible products..
     *
     */
    public function testGetNonEligibleProducts()
    {
    }

    /**
     * Test case for updateBatchNonEligibleProducts
     *
     * Update a batch of non-eligible products for a specific store, with a maximum limit of 100 products..
     *
     */
    public function testUpdateBatchNonEligibleProducts()
    {
    }
}
