<?php
/**
 * StampCardsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 28-02-2024 11:59
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DillerAPI;

use DillerAPI\Configuration;
use DillerAPI\ApiException;
use DillerAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StampCardsApiTest Class Doc Comment
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StampCardsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelStampReservation
     *
     * The 'cancel-reservation' endpoint is deprecated and should not be used, as it will be removed soon.
     *
     */
    public function testCancelStampReservation()
    {
    }

    /**
     * Test case for getMemberStampCards
     *
     * Get member active stamp cards.
     *
     */
    public function testGetMemberStampCards()
    {
    }

    /**
     * Test case for getStoreStamps
     *
     * Retrieves store stamp cards. By default it only retrieves active stamp cards..
     *
     */
    public function testGetStoreStamps()
    {
    }

    /**
     * Test case for reserveStamp
     *
     * This endpoint enables users to reserve a stamp for their pending orders,  thereby ensuring that the stamp cannot be used for any other transactions..
     *
     */
    public function testReserveStamp()
    {
    }
}
