<?php
/**
 * StoresApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Diller Retailer API
 *
 * The official Diller Retailer API (beta version) <br/> Last Updated: 27-02-2024 08:24
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.53
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DillerAPI;

use DillerAPI\Configuration;
use DillerAPI\ApiException;
use DillerAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * StoresApiTest Class Doc Comment
 *
 * @category Class
 * @package  DillerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StoresApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDepartment
     *
     * Add store department.
     *
     */
    public function testCreateDepartment()
    {
    }

    /**
     * Test case for get
     *
     * Gets store.
     *
     */
    public function testGet()
    {
    }

    /**
     * Test case for getAll
     *
     * Get all stores that the client has access to.
     *
     */
    public function testGetAll()
    {
    }

    /**
     * Test case for getDepartments
     *
     * Get store departments.
     *
     */
    public function testGetDepartments()
    {
    }

    /**
     * Test case for getSegments
     *
     * Retrieves all store's segments.
     *
     */
    public function testGetSegments()
    {
    }
}
